version: "3"
services:
  mongodb:
    image: bitnami/mongodb
    container_name: mongo-server
    networks:
      - mongo
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      PORT: "4500"
    ports:
      - "4500:4500"
    networks:
      - mongo
      - api
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      PORT: "5000"
    ports:
      - "5000:5000"
    networks:
      - api
networks:
  mongo:
  api:
